Repository wooriFisa-Final-Project-F4/api-gateway, pull requests merged in 2023-09, with the labels that each got.

#6 feature/#2-jwt-filter-gateway
  build.gradle
  src/main/java/f4/apigateway/constant/OpenApiEndpoints.java
  src/main/java/f4/apigateway/exception/CustomErrorCode.java
  src/main/java/f4/apigateway/filter/AuthenticationFilter.java
  src/main/java/f4/apigateway/filter/JwtAuthenticationFilter.java
  src/main/java/f4/apigateway/jwt/JwtTokenProvider.java
  src/main/java/f4/apigateway/jwt/exception/ExpiredTokenException.java
  src/main/java/f4/apigateway/jwt/exception/InvalidTokenException.java
Labels: enhancement

#8 fix/#1-jwt-authentication-filter
  src/main/java/f4/apigateway/config/AppConfig.java
  src/main/java/f4/apigateway/config/ErrorExceptionConfig.java
  src/main/java/f4/apigateway/config/RedisConfig.java
  src/main/java/f4/apigateway/exception/CustomErrorCode.java
  src/main/java/f4/apigateway/exception/ErrorDetails.java
  src/main/java/f4/apigateway/exception/GlobalExceptionHandler.java
  src/main/java/f4/apigateway/filter/JwtAuthenticationFilter.java
  src/main/java/f4/apigateway/jwt/JwtTokenProvider.java
  src/main/java/f4/apigateway/redis/RedisService.java
Labels: bug, enhancement

#11 [fix] [build] 배포 테스트 이후 변경사항 merge
  .gitignore
  build.gradle
  dockerfile
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/f4/apigateway/constant/OpenApiEndpoints.java
  src/main/java/f4/apigateway/exception/GlobalExceptionHandler.java
  src/main/resources/bootstrap.properties
Labels: documentation, enhancement

#12 [fix] OpenApiEndpoints 추가&변경
  src/main/java/f4/apigateway/constant/OpenApiEndpoints.java
Labels: enhancement

#13 [build] [test]
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/f4/apigateway/constant/OpenApiEndpoints.java
Labels: enhancement
